---
title: "NEON Data Access"
output: html_document
date: "2026-02-19"
---

# Import Packages

```{r load packages, message = FALSE}

#install.packages("tidyverse")
#install.packages("here")
#install.packages("neonUtilities")

library(tidyverse)
library(here)
library(neonUtilities)

```

***

# Define Data Products, Sites, and Dates

```{r set NEON conditions}

# Tick Pathogen Status
tick_pathogens <- "DP1.10092.001"

# Relative Humidity
relative_humidity <- "DP1.00098.001"

# Tick Abundance - drag cloth
tick_abundance <- "DP1.10093.001"

# Assigning two sites
my_sites <- c("HARV","DELA")

# Start date (as YYYY-MM)
start_date <- "2016-01"

# End date (as YYYY-MM)
end_date <- "2023-12"

```

***

# Import Data

## Tick Pathogen Status

### Import Tick Pathogens Data

```{r Pull Tick Pathogens, eval=FALSE}

# Pull Tick Pathogen data

list2env((loadByProduct(dpID = tick_pathogens,
                        site = my_sites,
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)

```

### Save Tick Pathogen Data

```{r save tick pathogen csv, eval=FALSE}

# Save variable file for tick pathogen status table

variables_10092 %>% 
  write_csv(here("data", "raw", "tick_pathogen_status_variable.csv"))

# Save data file with tick pathogen status information (Y/N)

tck_pathogen %>% 
  write_csv(here("data", "raw", "tick_pathogen_status_data.csv"))
```

## Tick Abundance Data

### Import Tick Abundance Data

```{r Pull Tick Abundance, eval=FALSE}

# Pull Tick Abundance data

list2env((loadByProduct(dpID = tick_abundance,
                        site = my_sites,
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)

```

### Save Tick Abundance Status

```{r save tick abundance csv, eval=FALSE}

# Save variable file for tick abundance table

variables_10093 %>% 
  write_csv(here("data", "raw", "tick_abundance_variable.csv"))

# Save data file with tick abundance data (numbers/count)

tck_fielddata %>% 
  write_csv(here("data", "raw", "tick_abundance_data.csv"))
```

## Relative Humidity Data

### Import Relative Temperature Data

```{r Pull Relative Temperature, eval=FALSE}

# Pull Relative Temperature data

list2env((loadByProduct(dpID = relative_humidity,
                        site = my_sites,
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)

```

### Save Relevant Temperature Data

```{r save relevant temperature csv, eval=FALSE}

# Save variable file for relative humidity data set

variables_00098 %>% 
  write_csv(here("data", "raw", "relative_humidity_variable.csv"))

# Save data file for relative humidity set
# WARNING!!!!! Large file that exceeds GitHub maximum file size - must be processed before pushing!!!

RH_30min %>%
  write_csv(here("data", "raw", "relative_humidity_data.csv"))

```
