---
title: "Statistical Analyses"
output: html_document
---

# The Relationship Between Seasonal Temperature and Tick Pathogen Abundance

------------------------------------------------------------------------

## Import Packages

```{r}

#install.packages("tidyverse")
#install.packages("here")
#install.packages("neonUtilities")
#install.packages("dplyr")
#install.packages("lubridate")

library(tidyverse)
library(here)
library(dplyr)
library(lubridate)
library(neonUtilities)

```

------------------------------------------------------------------------

## Load Raw Data

```{r, load data}

pathvtemp <- read_csv(here("data","processed","pathogen_vs_temp_data.csv"))

```
## Visualize Temperature vs. Pathogen Count

```{r create figure}

ggplot(
  data = pathvtemp,
  aes(
    x = mean_temp,
    y = pathogenCount)
  ) +
  geom_point() +
  facet_wrap(~siteID) +
theme_bw()

```

## Perform Regression

```{r, linear regression}

line_model <- lm(mean_temp ~ pathogenCount,
                 data = pathvtemp)

summary(line_model)
```



